<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>WPF_APP</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Company>Numidix Lab</Company>
    <Product>Club Manager Pro</Product>
    <Copyright>© 2026 Rouabah Mohamed Rafik</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Images\cadenas.png" />
    <None Remove="Assets\Images\ClubLOGO-Photoroom.png" />
    <None Remove="Assets\Images\CMS LOGO.png" />
    <None Remove="Assets\Images\football-trainer-teaching-his-pupils.jpg" />
    <None Remove="Assets\Images\logo-Photoroom.png" />
    <None Remove="Assets\Images\logo-Photoroom.psd" />
    <None Remove="Assets\Images\mot-de-passe.png" />
    <None Remove="Assets\Images\soccer-field-with-net-sun.jpg" />
    <None Remove="Assets\Images\utilisateur.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MCS.DTOs\CMS.DTOs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Fonts\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\cadenas.png" />
    <Resource Include="Assets\Images\ClubLOGO-Photoroom.png" />
    <Resource Include="Assets\Images\CMS LOGO.png" />
    <Resource Include="Assets\Images\football-trainer-teaching-his-pupils.jpg" />
    <Resource Include="Assets\Images\logo-Photoroom.png" />
    <Resource Include="Assets\Images\logo-Photoroom.psd" />
    <Resource Include="Assets\Images\mot-de-passe.png" />
    <Resource Include="Assets\Images\utilisateur.png" />
  </ItemGroup>

</Project>
